utils::globalVariables(c(
  "abstract","answer","answer.confirmed","answer.consensus","answer.created",
  "global_label_id",
  "lid",
  "conc",
  "aid",
  "answer.resolve","answer.updated","article.enabled","article.id","authors",
  "article_id","consensus","short_label","project_ordering","value_type","value","confirm_time",
  "resolve",
  "datasource.id","json_articles","keywords","lbl.consensus","lbl.enabled","lbl.id",
  "lbl.name","lbl.ordering","lbl.question","lbl.required","lbl.type",
  "primary_title","project.id","reviewer.id","reviewer.name","secondary_title",
  "updated","year","label_id",".",
  "concordance"))
